import { useEffect, useImperativeHandle, useRef, useState, type Ref } from 'react';
import { useLocale } from '../i18n';
export type AvatarCropperHandle={save:()=>Promise<void>};
export default function AvatarCropper({file,onDone,onCancel,onBusyChange,ref}:{file:File;onDone:(image:string)=>void|Promise<void>;onCancel:()=>void;onBusyChange?:(busy:boolean)=>void;ref?:Ref<AvatarCropperHandle>}){
 const {t}=useLocale(),canvas=useRef<HTMLCanvasElement>(null);const [image,setImage]=useState<HTMLImageElement|null>(null),[zoom,setZoom]=useState(1),[x,setX]=useState(0),[y,setY]=useState(0),[error,setError]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{if(active){if(img.naturalWidth*img.naturalHeight>40_000_000)setError(true);else setImage(img);}};img.onerror=()=>{if(active)setError(true);};img.src=url;return()=>{active=false;URL.revokeObjectURL(url);};},[file]);
 useEffect(()=>{if(!image||!canvas.current)return;const context=canvas.current.getContext('2d');if(!context)return;const side=Math.min(image.naturalWidth,image.naturalHeight)/zoom;const sx=(image.naturalWidth-side)*(x+1)/2,sy=(image.naturalHeight-side)*(y+1)/2;const resolution=Math.min(1024,Math.max(1,Math.ceil(side)));canvas.current.width=resolution;canvas.current.height=resolution;context.imageSmoothingEnabled=true;context.imageSmoothingQuality='high';context.drawImage(image,sx,sy,side,side,0,0,resolution,resolution);},[image,zoom,x,y]);
 const save=async()=>{if(!image||busy)return;setError(false);setBusy(true);onBusyChange?.(true);try{const outputCanvas=document.createElement('canvas');outputCanvas.width=128;outputCanvas.height=128;const context=outputCanvas.getContext('2d');if(!context)throw Error();const side=Math.min(image.naturalWidth,image.naturalHeight)/zoom;const sx=(image.naturalWidth-side)*(x+1)/2,sy=(image.naturalHeight-side)*(y+1)/2;context.imageSmoothingEnabled=true;context.imageSmoothingQuality='high';context.drawImage(image,sx,sy,side,side,0,0,128,128);let output:Blob|null=null;for(const q of [.85,.7,.55,.4]){output=await new Promise<Blob|null>(resolve=>outputCanvas.toBlob(resolve,'image/webp',q));if(output&&output.type==='image/webp'&&output.size<=20480)break;}if(!output||output.type!=='image/webp'||output.size>20480){output=await new Promise<Blob|null>(resolve=>outputCanvas.toBlob(resolve,'image/png'));if(!output||output.type!=='image/png'||output.size>70000)throw Error();}const encoded=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error());reader.readAsDataURL(output);});await onDone(encoded);}catch{setError(true);}finally{setBusy(false);onBusyChange?.(false);}};
 useImperativeHandle(ref,()=>({save}));
 return <section className="avatar-cropper"><h3>{t('Crop avatar')}</h3><canvas ref={canvas} width={128} height={128}/>{[['Zoom',zoom,1,3,setZoom],['Horizontal',x,-1,1,setX],['Vertical',y,-1,1,setY]].map(([label,value,min,max,set])=><label key={String(label)}>{t(String(label))}<input type="range" min={Number(min)} max={Number(max)} step="0.05" value={Number(value)} onChange={e=>(set as (n:number)=>void)(Number(e.target.value))}/></label>)}{error&&<p role="alert">{t('Could not process image. Choose another image.')}</p>}<button type="button" disabled={busy} onClick={onCancel}>{t('Cancel')}</button></section>;
}
