import { useEffect, useRef, useState } from 'react';
import { useLocale } from '../i18n';
export default function AvatarCropper({file,onDone,onCancel}:{file:File;onDone:(image:string)=>void;onCancel:()=>void}){
 const {t}=useLocale(),canvas=useRef<HTMLCanvasElement>(null);const [image,setImage]=useState<HTMLImageElement|null>(null),[zoom,setZoom]=useState(1),[x,setX]=useState(0),[y,setY]=useState(0),[error,setError]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{if(active){if(img.naturalWidth*img.naturalHeight>40_000_000)setError(true);else setImage(img);}};img.onerror=()=>{if(active)setError(true);};img.src=url;return()=>{active=false;URL.revokeObjectURL(url);};},[file]);
 useEffect(()=>{if(!image||!canvas.current)return;const context=canvas.current.getContext('2d');if(!context)return;const side=Math.min(image.naturalWidth,image.naturalHeight)/zoom;const sx=(image.naturalWidth-side)*(x+1)/2,sy=(image.naturalHeight-side)*(y+1)/2;context.clearRect(0,0,128,128);context.drawImage(image,sx,sy,side,side,0,0,128,128);},[image,zoom,x,y]);
 const save=async()=>{if(!canvas.current||busy)return;setBusy(true);try{let output:Blob|null=null;for(const q of [.85,.7,.55,.4]){output=await new Promise<Blob|null>(resolve=>canvas.current!.toBlob(resolve,'image/webp',q));if(output&&output.type==='image/webp'&&output.size<=20480)break;}if(!output||output.type!=='image/webp'||output.size>20480)throw Error();const reader=new FileReader();reader.onload=()=>onDone(String(reader.result));reader.onerror=()=>setError(true);reader.readAsDataURL(output);}catch{setError(true);}finally{setBusy(false);}};
 return <section className="avatar-cropper"><h3>{t('Crop avatar')}</h3><canvas ref={canvas} width={128} height={128}/>{[['Zoom',zoom,1,3,setZoom],['Horizontal',x,-1,1,setX],['Vertical',y,-1,1,setY]].map(([label,value,min,max,set])=><label key={String(label)}>{t(String(label))}<input type="range" min={Number(min)} max={Number(max)} step="0.05" value={Number(value)} onChange={e=>(set as (n:number)=>void)(Number(e.target.value))}/></label>)}{error&&<p role="alert">{t('Could not process image. Choose another image.')}</p>}<button type="button" disabled={!image||busy||error} onClick={()=>void save()}>{t('Use cropped image')}</button><button type="button" onClick={onCancel}>{t('Cancel')}</button></section>;
}
