const keys = [
  'Reactor weapon',
  'Hit each turret until its metal glows red, orange and finally white-hot before it explodes. Every turret gives extra points; the hull stays protected until all are destroyed.',
  'After all turrets explode, a concealed central weapon opens. Attack the now vulnerable hull and dodge its pulses.',
  'During the reactor weapon phase, small escorts return in waves. The pauses shorten as levels rise; from level 50, the next wave enters as soon as the previous one is cleared.',
];
const rows: Record<string, string[]> = {
  de: ['Reaktorwaffe', 'Triff jedes Geschütz, bis sein Metall rot, orange und schließlich weißglühend wird und es explodiert. Jedes Geschütz gibt Extrapunkte; der Rumpf bleibt geschützt, bis alle zerstört sind.', 'Sind alle Geschütze zerstört, öffnet sich eine verdeckte Waffe in der Schiffsmitte. Greife den nun verwundbaren Rumpf an und weiche ihren Impulsen aus.', 'Während der Reaktorwaffenphase kommen kleine Begleitschiffe in Wellen nach. Die Pausen werden mit höheren Levels kürzer; ab Level 50 beginnt die nächste Welle sofort, sobald die vorherige abgeschossen ist.'],
  es: ['Arma del reactor', 'Dispara a cada torreta hasta que su metal brille rojo, naranja y finalmente blanco antes de explotar. Cada torreta da puntos extra; el casco sigue protegido hasta destruirlas todas.', 'Cuando todas las torretas explotan, se abre un arma central oculta. Ataca el casco vulnerable y esquiva sus pulsos.', 'Durante la fase del arma del reactor, pequeñas escoltas regresan en oleadas. Las pausas se acortan con el nivel; desde el nivel 50, la siguiente oleada entra en cuanto eliminas la anterior.'],
  fr: ['Arme du réacteur', 'Touche chaque tourelle jusqu’à ce que son métal rougisse, devienne orange puis incandescent avant d’exploser. Chaque tourelle rapporte des points bonus ; la coque reste protégée jusqu’à leur destruction complète.', 'Après la destruction des tourelles, une arme centrale dissimulée se déploie. Attaque la coque devenue vulnérable et évite ses impulsions.', 'Pendant la phase de l’arme du réacteur, de petites escortes reviennent par vagues. Les pauses raccourcissent avec les niveaux ; dès le niveau 50, la vague suivante arrive aussitôt la précédente éliminée.'],
  pt: ['Arma do reator', 'Atinge cada torreta até o metal brilhar vermelho, laranja e finalmente branco antes de explodir. Cada torreta dá pontos extra; o casco fica protegido até todas serem destruídas.', 'Após a destruição das torretas, abre-se uma arma central escondida. Ataca o casco agora vulnerável e desvia-te dos seus pulsos.', 'Na fase da arma do reator, pequenas escoltas regressam em vagas. As pausas diminuem com os níveis; a partir do nível 50, a próxima vaga entra assim que a anterior é eliminada.'],
  it: ['Arma del reattore', 'Colpisci ogni torretta finché il metallo diventa rosso, arancione e infine incandescente prima di esplodere. Ogni torretta dà punti extra; lo scafo resta protetto finché non sono tutte distrutte.', 'Dopo la distruzione delle torrette, si apre un’arma centrale nascosta. Attacca lo scafo ora vulnerabile e schiva i suoi impulsi.', 'Nella fase dell’arma del reattore tornano piccole scorte a ondate. Le pause si accorciano con i livelli; dal livello 50, la nuova ondata entra subito dopo l’eliminazione della precedente.'],
  pl: ['Broń reaktora', 'Trafiaj każdą wieżyczkę, aż jej metal rozgrzeje się do czerwoności, pomarańczu i bieli, po czym wybuchnie. Każda daje dodatkowe punkty; kadłub jest chroniony do zniszczenia wszystkich.', 'Po zniszczeniu wieżyczek wysuwa się ukryta broń centralna. Atakuj odsłonięty kadłub i unikaj jej impulsów.', 'W fazie broni reaktora małe eskorty wracają falami. Przerwy skracają się wraz z poziomami; od poziomu 50 następna fala nadlatuje natychmiast po zniszczeniu poprzedniej.'],
  tr: ['Reaktör silahı', 'Her tarete, metali kırmızı, turuncu ve sonunda beyaz parlayıp patlayana kadar ateş et. Her taret ek puan verir; hepsi yok olana kadar gövde korunur.', 'Tüm taretler yok olunca gizli merkez silahı açılır. Artık savunmasız olan gövdeye saldır ve darbelerden kaç.', 'Reaktör silahı aşamasında küçük eskortlar dalgalar halinde gelir. Seviyeler yükseldikçe aralar kısalır; 50. seviyeden itibaren önceki dalga bitince yenisi hemen gelir.'],
  ru: ['Оружие реактора', 'Стреляй по каждой турели, пока металл не раскалится до красного, оранжевого и белого цвета перед взрывом. Каждая турель даёт очки; корпус защищён до уничтожения всех турелей.', 'После уничтожения турелей открывается скрытое центральное оружие. Атакуй уязвимый корпус и уклоняйся от импульсов.', 'В фазе оружия реактора маленькие эскорты возвращаются волнами. С ростом уровня паузы сокращаются; с уровня 50 новая волна появляется сразу после уничтожения предыдущей.'],
  hr: ['Reaktorsko oružje', 'Pogađaj svaku kupolu dok metal ne zasja crveno, narančasto i bijelo prije eksplozije. Svaka daje dodatne bodove; trup ostaje zaštićen dok sve nisu uništene.', 'Nakon uništenja svih kupola otvara se skriveno središnje oružje. Napadni sada ranjiv trup i izbjegavaj impulse.', 'U fazi reaktorskog oružja male pratnje dolaze u valovima. Stanke se skraćuju s razinama; od razine 50 novi val stiže odmah nakon uništenja prethodnog.'],
  cs: ['Reaktorová zbraň', 'Zasahuj každou věž, dokud kov nezáří červeně, oranžově a nakonec bíle před explozí. Každá věž dává body navíc; trup zůstává chráněn do zničení všech věží.', 'Po zničení všech věží se otevře skrytá centrální zbraň. Útoč na nyní zranitelný trup a vyhýbej se pulzům.', 'Ve fázi reaktorové zbraně přilétají malé doprovody ve vlnách. Přestávky se s úrovněmi zkracují; od úrovně 50 další vlna začíná ihned po zničení předchozí.'],
  sk: ['Reaktorová zbraň', 'Zasahuj každú vežu, kým kov nezažiari červeno, oranžovo a napokon bielo pred výbuchom. Každá dáva body navyše; trup je chránený do zničenia všetkých veží.', 'Po zničení všetkých veží sa otvorí skrytá centrálna zbraň. Útoč na teraz zraniteľný trup a vyhýbaj sa pulzom.', 'Vo fáze reaktorovej zbrane prilietajú malé sprievody vo vlnách. Prestávky sa s úrovňami skracujú; od úrovne 50 ďalšia vlna začína hneď po zničení predchádzajúcej.'],
  hu: ['Reaktorfegyver', 'Lődd a tornyokat, amíg fémük vörösen, narancssárgán, végül fehéren izzik a robbanás előtt. Mindegyik extra pontot ad; a hajótest mindegyik torony elpusztításáig védett.', 'Az összes torony elpusztítása után kinyílik egy rejtett központi fegyver. Támadd a sebezhető hajótestet és kerüld az impulzusait.', 'A reaktorfegyver szakaszában kis kísérők érkeznek hullámokban. A szünetek a szintekkel rövidülnek; az 50. szinttől az előző hullám legyőzése után rögtön jön a következő.'],
  ro: ['Arma reactorului', 'Lovește fiecare turelă până când metalul strălucește roșu, portocaliu și apoi alb înainte să explodeze. Fiecare oferă puncte suplimentare; coca rămâne protejată până sunt distruse toate.', 'După distrugerea turelelor se deschide o armă centrală ascunsă. Atacă coca acum vulnerabilă și evită impulsurile.', 'În faza armei reactorului, escorte mici revin în valuri. Pauzele scad odată cu nivelul; de la nivelul 50 următorul val sosește imediat după eliminarea celui precedent.'],
  sr: ['Реакторско оружје', 'Погађај сваку куполу док метал не засија црвено, наранџасто и бело пре експлозије. Свака даје додатне поене; труп је заштићен док све нису уништене.', 'После уништења свих купола отвара се скривено централно оружје. Нападни сада рањив труп и избегавај импулсе.', 'У фази реакторског оружја мале пратње долазе у таласима. Паузе се скраћују с нивоима; од нивоа 50 нови талас стиже одмах после уништења претходног.'],
  uk: ['Зброя реактора', 'Влучай у кожну турель, доки метал не розжариться до червоного, помаранчевого та білого кольору перед вибухом. Кожна дає додаткові очки; корпус захищений до знищення всіх турелей.', 'Після знищення всіх турелей відкривається прихована центральна зброя. Атакуй тепер вразливий корпус і ухиляйся від імпульсів.', 'У фазі зброї реактора малі ескорти повертаються хвилями. Паузи скорочуються зі зростанням рівня; з рівня 50 наступна хвиля прибуває відразу після знищення попередньої.'],
  th: ['อาวุธเครื่องปฏิกรณ์', 'ยิงป้อมปืนแต่ละป้อมจนโลหะร้อนเป็นสีแดง สีส้ม และสีขาวก่อนระเบิด แต่ละป้อมให้คะแนนพิเศษ ตัวเรือยังได้รับการป้องกันจนกว่าจะทำลายครบทุกป้อม', 'เมื่อทำลายป้อมปืนทั้งหมด อาวุธที่ซ่อนอยู่ตรงกลางยานจะเปิดออก โจมตีตัวเรือที่อ่อนแอลงและหลบพัลส์ของมัน', 'ในช่วงอาวุธเครื่องปฏิกรณ์ ยานคุ้มกันขนาดเล็กจะกลับมาเป็นระลอก ช่วงพักสั้นลงตามระดับ ตั้งแต่ระดับ 50 ระลอกใหม่จะเข้ามาทันทีเมื่อกำจัดระลอกก่อนหมด'],
};
export const bossWeaponTranslations = Object.fromEntries(Object.entries(rows).map(([locale, values]) => [locale, Object.fromEntries(keys.map((key, index) => [key, values[index]]))]));
