const keys = [
  'Turret {number}',
  'Hull protected',
  'Reactor exposed',
  'Destroy every turret first — hull protected.',
  'Reactor exposed — attack the hull and dodge pulses!',
  'First destroy every turret, each with its own green energy bar and extra points. The hull is protected, even from bombs. After the last turret falls, the boss energy bar appears: attack the hull and dodge the reactor pulses.',
];
const rows: Record<string, string[]> = {
  de: ['Geschütz {number}', 'Rumpf geschützt', 'Reaktor freigelegt', 'Zuerst alle Geschütze zerstören – Rumpf geschützt.', 'Reaktor freigelegt – Rumpf angreifen und Impulsen ausweichen!', 'Zerstöre zuerst alle Geschütze. Jedes hat einen eigenen grünen Energiebalken und gibt zusätzliche Punkte. Der Rumpf ist geschützt, auch vor Bomben. Nach dem letzten Geschütz erscheint der Energiebalken des Bosses: Greife den Rumpf an und weiche den Reaktorimpulsen aus.'],
  es: ['Torreta {number}', 'Casco protegido', 'Reactor expuesto', 'Destruye primero todas las torretas: casco protegido.', '¡Reactor expuesto: ataca el casco y esquiva los pulsos!', 'Destruye primero todas las torretas; cada una tiene su propia barra de energía verde y otorga puntos extra. El casco está protegido, incluso de las bombas. Al caer la última torreta, aparece la barra de energía del jefe: ataca el casco y esquiva los pulsos del reactor.'],
  fr: ['Tourelle {number}', 'Coque protégée', 'Réacteur exposé', 'Détruis toutes les tourelles d’abord : coque protégée.', 'Réacteur exposé : attaque la coque et évite les impulsions !', 'Détruis d’abord toutes les tourelles, chacune avec sa barre d’énergie verte et ses points bonus. La coque est protégée, même contre les bombes. Après la dernière tourelle, la barre d’énergie du boss apparaît : attaque la coque et évite les impulsions du réacteur.'],
  pt: ['Torreta {number}', 'Casco protegido', 'Reator exposto', 'Destrói primeiro todas as torretas: casco protegido.', 'Reator exposto: ataca o casco e desvia-te dos pulsos!', 'Destrói primeiro todas as torretas, cada uma com a sua barra de energia verde e pontos extra. O casco está protegido, mesmo contra bombas. Quando a última torreta cair, aparece a barra de energia do chefe: ataca o casco e desvia-te dos pulsos do reator.'],
  it: ['Torretta {number}', 'Scafo protetto', 'Reattore esposto', 'Distruggi prima tutte le torrette: scafo protetto.', 'Reattore esposto: attacca lo scafo e schiva gli impulsi!', 'Distruggi prima tutte le torrette, ciascuna con la propria barra di energia verde e punti extra. Lo scafo è protetto, anche dalle bombe. Dopo l’ultima torretta appare la barra di energia del boss: attacca lo scafo e schiva gli impulsi del reattore.'],
  pl: ['Wieżyczka {number}', 'Kadłub chroniony', 'Reaktor odsłonięty', 'Najpierw zniszcz wszystkie wieżyczki — kadłub chroniony.', 'Reaktor odsłonięty — atakuj kadłub i unikaj impulsów!', 'Najpierw zniszcz wszystkie wieżyczki, każdą z własnym zielonym paskiem energii i dodatkowymi punktami. Kadłub jest chroniony, także przed bombami. Po zniszczeniu ostatniej wieżyczki pojawia się pasek energii bossa: atakuj kadłub i unikaj impulsów reaktora.'],
  tr: ['Taret {number}', 'Gövde korumalı', 'Reaktör açığa çıktı', 'Önce tüm taretleri yok et — gövde korumalı.', 'Reaktör açığa çıktı — gövdeye saldır ve darbelere yakalanma!', 'Önce tüm taretleri yok et; her birinin yeşil enerji çubuğu ve ek puanı vardır. Gövde bombalara karşı bile korumalıdır. Son taret yok olunca bossun enerji çubuğu belirir: gövdeye saldır ve reaktör darbelerinden kaç.'],
  ru: ['Турель {number}', 'Корпус защищён', 'Реактор открыт', 'Сначала уничтожь все турели — корпус защищён.', 'Реактор открыт — атакуй корпус и уклоняйся от импульсов!', 'Сначала уничтожь все турели: у каждой своя зелёная полоска энергии и дополнительные очки. Корпус защищён даже от бомб. После последней турели появляется полоска энергии босса: атакуй корпус и уклоняйся от импульсов реактора.'],
  hr: ['Kupola {number}', 'Trup zaštićen', 'Reaktor otkriven', 'Prvo uništi sve kupole — trup je zaštićen.', 'Reaktor otkriven — napadni trup i izbjegavaj impulse!', 'Prvo uništi sve kupole, svaku s vlastitom zelenom trakom energije i dodatnim bodovima. Trup je zaštićen čak i od bombi. Nakon zadnje kupole pojavljuje se traka energije šefa: napadni trup i izbjegavaj impulse reaktora.'],
  cs: ['Věž {number}', 'Trup chráněn', 'Reaktor odkryt', 'Nejprve znič všechny věže — trup je chráněn.', 'Reaktor odkryt — útoč na trup a vyhýbej se pulzům!', 'Nejprve znič všechny věže, každou s vlastním zeleným ukazatelem energie a body navíc. Trup je chráněn i před bombami. Po poslední věži se objeví ukazatel energie bosse: útoč na trup a vyhýbej se pulzům reaktoru.'],
  sk: ['Veža {number}', 'Trup chránený', 'Reaktor odkrytý', 'Najprv znič všetky veže — trup je chránený.', 'Reaktor odkrytý — útoč na trup a vyhýbaj sa pulzom!', 'Najprv znič všetky veže, každú s vlastným zeleným ukazovateľom energie a bodmi navyše. Trup je chránený aj pred bombami. Po poslednej veži sa objaví ukazovateľ energie bossa: útoč na trup a vyhýbaj sa pulzom reaktora.'],
  hu: ['Lövegtorony {number}', 'Védett hajótest', 'Reaktor szabaddá vált', 'Először pusztítsd el az összes lövegtornyot — a hajótest védett.', 'Reaktor szabaddá vált — támadd a hajótestet és kerüld a löketeket!', 'Először pusztítsd el az összes lövegtornyot; mindegyik saját zöld energiacsíkkal és extra pontokkal rendelkezik. A hajótest még a bombáktól is védett. Az utolsó torony után megjelenik a főellenfél energiacsíkja: támadd a hajótestet és kerüld a reaktor löketeit.'],
  ro: ['Turelă {number}', 'Cocă protejată', 'Reactor expus', 'Distruge mai întâi toate turelele — coca este protejată.', 'Reactor expus — atacă coca și evită impulsurile!', 'Distruge mai întâi toate turelele, fiecare cu propria bară verde de energie și puncte suplimentare. Coca este protejată chiar și de bombe. După ultima turelă apare bara de energie a bossului: atacă coca și evită impulsurile reactorului.'],
  sr: ['Купола {number}', 'Труп заштићен', 'Реактор откривен', 'Прво уништи све куполе — труп је заштићен.', 'Реактор откривен — нападни труп и избегавај импулсе!', 'Прво уништи све куполе, сваку са сопственом зеленом траком енергије и додатним поенима. Труп је заштићен чак и од бомби. После последње куполе појављује се трака енергије боса: нападни труп и избегавај импулсе реактора.'],
  uk: ['Турель {number}', 'Корпус захищений', 'Реактор відкрито', 'Спершу знищ усі турелі — корпус захищений.', 'Реактор відкрито — атакуй корпус і ухиляйся від імпульсів!', 'Спершу знищ усі турелі: кожна має власну зелену смужку енергії та додаткові очки. Корпус захищений навіть від бомб. Після останньої турелі з’являється смужка енергії боса: атакуй корпус і ухиляйся від імпульсів реактора.'],
  th: ['ป้อมปืน {number}', 'ตัวเรือได้รับการป้องกัน', 'เครื่องปฏิกรณ์ถูกเปิดเผย', 'ทำลายป้อมปืนทั้งหมดก่อน — ตัวเรือยังได้รับการป้องกัน', 'เครื่องปฏิกรณ์ถูกเปิดเผย — โจมตีตัวเรือและหลบพัลส์!', 'ทำลายป้อมปืนทั้งหมดก่อน แต่ละป้อมมีแถบพลังงานสีเขียวและให้คะแนนพิเศษ ตัวเรือได้รับการป้องกันแม้แต่จากระเบิด เมื่อป้อมสุดท้ายถูกทำลาย แถบพลังงานของบอสจะปรากฏ ให้โจมตีตัวเรือและหลบพัลส์จากเครื่องปฏิกรณ์'],
};
export const bossPhaseTranslations = Object.fromEntries(Object.entries(rows).map(([locale, values]) => [locale, Object.fromEntries(keys.map((key, index) => [key, values[index]]))]));
