import type { Locale } from './config.ts';

export const collectionEquipmentKeys = [
  '{value0} of 3 stars', 'Upgrade · {value0}',
  'Hull protection absorbs {value0} enemy projectile hits per life. It does not protect against direct ship collisions.',
  'Central weapon: pulse, calibre 8. Initial warning 1.8 s; then {value0} s volley interval.',
  'Single shots alternate with {value0}-shot fans.', 'SHIP HISTORY', 'CURRENT EQUIPMENT',
  'COLLECTOR CARD · Fiction from the Cryptoid universe / actual game stats · Edition 01',
] as const;
const rows: Partial<Record<Locale, string>> = {
 de: '{value0} von 3 Sternen|Aufrüstung · {value0}|Der Rumpfschutz fängt {value0} gegnerische Projektiltreffer pro Leben ab. Er schützt nicht vor direkten Schiffskollisionen.|Zentralwaffe: Impuls, Kaliber 8. Erste Warnung: 1,8 s; danach {value0} s Salvenabstand.|Einzelschüsse wechseln mit {value0}-fachen Fächern.|SCHIFFSGESCHICHTE|AKTUELLE AUSRÜSTUNG|SAMMELKARTE · Fiktion aus dem Cryptoid-Universum / tatsächliche Spielwerte · Edition 01',
 es: '{value0} de 3 estrellas|Mejora · {value0}|La protección del casco absorbe {value0} impactos de proyectiles enemigos por vida. No protege contra colisiones directas entre naves.|Arma central: pulso, calibre 8. Aviso inicial de 1,8 s; después, {value0} s entre salvas.|Los disparos individuales alternan con abanicos de {value0} disparos.|HISTORIA DE LA NAVE|EQUIPO ACTUAL|CARTA DE COLECCIÓN · Ficción del universo Cryptoid / estadísticas reales del juego · Edición 01',
 fr: '{value0} sur 3 étoiles|Amélioration · {value0}|La protection de la coque absorbe {value0} impacts de projectiles ennemis par vie. Elle ne protège pas contre les collisions directes entre vaisseaux.|Arme centrale : impulsion, calibre 8. Alerte initiale de 1,8 s ; puis {value0} s entre les salves.|Les tirs simples alternent avec des éventails de {value0} tirs.|HISTOIRE DU VAISSEAU|ÉQUIPEMENT ACTUEL|CARTE DE COLLECTION · Fiction de l’univers Cryptoid / statistiques réelles du jeu · Édition 01',
 pt: '{value0} de 3 estrelas|Melhoria · {value0}|A proteção do casco absorve {value0} impactos de projéteis inimigos por vida. Não protege contra colisões diretas entre naves.|Arma central: pulso, calibre 8. Aviso inicial de 1,8 s; depois, {value0} s entre salvas.|Os disparos individuais alternam com leques de {value0} disparos.|HISTÓRIA DA NAVE|EQUIPAMENTO ATUAL|CARTA DE COLEÇÃO · Ficção do universo Cryptoid / estatísticas reais do jogo · Edição 01',
 it: '{value0} su 3 stelle|Potenziamento · {value0}|La protezione dello scafo assorbe {value0} colpi di proiettili nemici per vita. Non protegge dalle collisioni dirette tra navi.|Arma centrale: impulso, calibro 8. Avviso iniziale di 1,8 s; poi {value0} s tra le salve.|I colpi singoli si alternano a ventagli di {value0} colpi.|STORIA DELLA NAVE|EQUIPAGGIAMENTO ATTUALE|CARTA DA COLLEZIONE · Storia fittizia dell’universo Cryptoid / statistiche reali del gioco · Edizione 01',
 pl: '{value0} z 3 gwiazdek|Ulepszenie · {value0}|Ochrona kadłuba pochłania {value0} trafień pociskami wroga na życie. Nie chroni przed bezpośrednimi zderzeniami statków.|Broń centralna: impuls, kaliber 8. Pierwsze ostrzeżenie: 1,8 s; następnie {value0} s między salwami.|Pojedyncze strzały przeplatają się z wachlarzami po {value0} strzałów.|HISTORIA STATKU|AKTUALNE WYPOSAŻENIE|KARTA KOLEKCJONERSKA · Fikcja uniwersum Cryptoid / rzeczywiste statystyki gry · Edycja 01',
 tr: '3 yıldızdan {value0}|Yükseltme · {value0}|Gövde koruması her can için {value0} düşman mermisi isabetini soğurur. Doğrudan gemi çarpışmalarına karşı korumaz.|Merkez silah: darbe, kalibre 8. İlk uyarı 1,8 sn; ardından salvolar arasında {value0} sn.|Tekli atışlar, {value0} atışlık yelpazelerle dönüşümlü yapılır.|GEMİNİN HİKÂYESİ|MEVCUT DONANIM|KOLEKSİYON KARTI · Cryptoid evreninden kurgu / gerçek oyun istatistikleri · Sürüm 01',
 ru: '{value0} из 3 звёзд|Улучшение · {value0}|Защита корпуса поглощает {value0} попаданий вражеских снарядов на жизнь. Она не защищает от прямых столкновений кораблей.|Центральное оружие: импульс, калибр 8. Первое предупреждение: 1,8 с; затем {value0} с между залпами.|Одиночные выстрелы чередуются с веерами по {value0} выстрелов.|ИСТОРИЯ КОРАБЛЯ|ТЕКУЩЕЕ ОСНАЩЕНИЕ|КОЛЛЕКЦИОННАЯ КАРТА · Вымысел вселенной Cryptoid / реальные игровые показатели · Издание 01',
 hr: '{value0} od 3 zvjezdice|Nadogradnja · {value0}|Zaštita trupa upija {value0} pogodaka neprijateljskih projektila po životu. Ne štiti od izravnih sudara brodova.|Središnje oružje: impuls, kalibar 8. Prvo upozorenje: 1,8 s; zatim {value0} s između salvi.|Pojedinačni hici izmjenjuju se s lepezama od {value0} hitaca.|POVIJEST BRODA|TRENUTAČNA OPREMA|KOLEKCIONARSKA KARTA · Fikcija iz svemira Cryptoid / stvarne vrijednosti igre · Izdanje 01',
 cs: '{value0} ze 3 hvězd|Vylepšení · {value0}|Ochrana trupu pohltí {value0} zásahů nepřátelskými projektily na život. Nechrání před přímými srážkami lodí.|Centrální zbraň: impuls, ráže 8. První varování: 1,8 s; poté {value0} s mezi salvami.|Jednotlivé výstřely se střídají s vějíři po {value0} výstřelech.|PŘÍBĚH LODI|AKTUÁLNÍ VYBAVENÍ|SBĚRATELSKÁ KARTA · Fikce ze světa Cryptoid / skutečné herní hodnoty · Edice 01',
 sk: '{value0} z 3 hviezd|Vylepšenie · {value0}|Ochrana trupu pohltí {value0} zásahov nepriateľskými projektilmi na život. Nechráni pred priamymi zrážkami lodí.|Centrálna zbraň: impulz, kaliber 8. Prvé varovanie: 1,8 s; potom {value0} s medzi salvami.|Jednotlivé výstrely sa striedajú s vejármi po {value0} výstreloch.|PRÍBEH LODE|AKTUÁLNE VYBAVENIE|ZBERATEĽSKÁ KARTA · Fikcia zo sveta Cryptoid / skutočné herné hodnoty · Edícia 01',
 hu: '{value0} a 3 csillagból|Fejlesztés · {value0}|A hajótest védelme életenként {value0} ellenséges lövedéktalálatot nyel el. Közvetlen hajóütközéstől nem véd.|Központi fegyver: impulzus, 8-as kaliber. Első figyelmeztetés: 1,8 mp; utána {value0} mp a sortüzek között.|Az egyes lövések {value0} lövéses legyezőkkel váltakoznak.|A HAJÓ TÖRTÉNETE|JELENLEGI FELSZERELÉS|GYŰJTŐKÁRTYA · Fikció a Cryptoid univerzumából / tényleges játékértékek · 01. kiadás',
 ro: '{value0} din 3 stele|Îmbunătățire · {value0}|Protecția carenei absoarbe {value0} lovituri de proiectile inamice per viață. Nu protejează împotriva coliziunilor directe dintre nave.|Armă centrală: impuls, calibru 8. Primul avertisment: 1,8 s; apoi {value0} s între salve.|Focurile individuale alternează cu evantaie de {value0} focuri.|POVESTEA NAVEI|ECHIPAMENT ACTUAL|CARTE DE COLECȚIE · Ficțiune din universul Cryptoid / valori reale ale jocului · Ediția 01',
 sr: '{value0} од 3 звездице|Надоградња · {value0}|Заштита трупа упија {value0} погодака непријатељских пројектила по животу. Не штити од директних судара бродова.|Централно оружје: импулс, калибар 8. Прво упозорење: 1,8 с; затим {value0} с између салви.|Појединачни хици смењују се са лепезама од {value0} хитаца.|ПРИЧА БРОДА|ТРЕНУТНА ОПРЕМА|КОЛЕКЦИОНАРСКА КАРТА · Фикција из универзума Cryptoid / стварне вредности игре · Издање 01',
 uk: '{value0} із 3 зірок|Поліпшення · {value0}|Захист корпусу поглинає {value0} влучань ворожих снарядів на життя. Він не захищає від прямих зіткнень кораблів.|Центральна зброя: імпульс, калібр 8. Перше попередження: 1,8 с; потім {value0} с між залпами.|Одиночні постріли чергуються з віялами по {value0} пострілів.|ІСТОРІЯ КОРАБЛЯ|ПОТОЧНЕ ОСНАЩЕННЯ|КОЛЕКЦІЙНА КАРТКА · Вигадка зі всесвіту Cryptoid / реальні ігрові показники · Видання 01',
 th: '{value0} จาก 3 ดาว|การอัปเกรด · {value0}|เกราะตัวเรือรับการโจมตีจากกระสุนศัตรูได้ {value0} ครั้งต่อหนึ่งชีวิต ไม่ป้องกันการชนกับยานโดยตรง|อาวุธกลาง: พัลส์ ขนาด 8 เตือนครั้งแรก 1.8 วินาที จากนั้นเว้นระยะ {value0} วินาทีระหว่างชุดยิง|การยิงเดี่ยวสลับกับการยิงแบบพัด {value0} นัด|ประวัติยาน|อุปกรณ์ปัจจุบัน|การ์ดสะสม · เรื่องแต่งจากจักรวาล Cryptoid / ค่าสถิติจริงในเกม · ฉบับ 01',
 zh: '{value0}/3 星|升级 · {value0}|舰体防护每条生命可吸收 {value0} 次敌方弹丸命中。它不能防止飞船直接碰撞。|中央武器：脉冲，口径 8。首次预警 1.8 秒；随后齐射间隔为 {value0} 秒。|单发射击与 {value0} 发扇形射击交替进行。|飞船故事|当前装备|收藏卡 · Cryptoid 宇宙的虚构故事 / 实际游戏数值 · 第 01 版',
 vi: '{value0} trên 3 sao|Nâng cấp · {value0}|Lớp bảo vệ thân tàu hấp thụ {value0} lần trúng đạn của địch mỗi mạng. Không bảo vệ trước va chạm trực tiếp giữa các tàu.|Vũ khí trung tâm: xung, cỡ nòng 8. Cảnh báo đầu tiên 1,8 giây; sau đó cách {value0} giây giữa các loạt bắn.|Bắn đơn xen kẽ với loạt {value0} phát hình quạt.|CÂU CHUYỆN CON TÀU|TRANG BỊ HIỆN TẠI|THẺ SƯU TẦM · Truyện hư cấu trong vũ trụ Cryptoid / chỉ số thực tế trong trò chơi · Phiên bản 01',
 id: '{value0} dari 3 bintang|Peningkatan · {value0}|Pelindung lambung menyerap {value0} hantaman proyektil musuh per nyawa. Tidak melindungi dari tabrakan langsung antarkapal.|Senjata pusat: pulsa, kaliber 8. Peringatan pertama 1,8 detik; lalu {value0} detik antar rentetan.|Tembakan tunggal bergantian dengan kipas {value0} tembakan.|KISAH KAPAL|PERLENGKAPAN SAAT INI|KARTU KOLEKSI · Fiksi dari alam semesta Cryptoid / statistik permainan sebenarnya · Edisi 01',
 ko: '별 3개 중 {value0}개|업그레이드 · {value0}|선체 보호는 목숨마다 적 투사체 명중을 {value0}회 흡수합니다. 함선의 직접 충돌은 막지 못합니다.|중앙 무기: 펄스, 구경 8. 첫 경고는 1.8초이며, 이후 일제 사격 간격은 {value0}초입니다.|단발 사격과 {value0}발 부채꼴 사격이 번갈아 나옵니다.|함선 이야기|현재 장비|수집 카드 · Cryptoid 세계의 허구 이야기 / 실제 게임 수치 · 제01판',
 ja: '星3個中{value0}個|アップグレード · {value0}|船体防護はライフごとに敵の弾丸の命中を{value0}回吸収します。艦船との直接衝突は防げません。|中央武器：パルス、口径8。最初の警告は1.8秒、その後の一斉射撃間隔は{value0}秒です。|単発射撃と{value0}発の扇状射撃を交互に行います。|艦船の物語|現在の装備|収集カード · Cryptoid世界の架空の物語 / 実際のゲーム数値 · 第01版',
 hi: '3 में से {value0} तारे|उन्नयन · {value0}|ढाँचे का सुरक्षा कवच हर जीवन में दुश्मन के प्रक्षेप्यों की {value0} चोटें रोकता है। यह जहाज़ों की सीधी टक्कर से नहीं बचाता।|केंद्रीय हथियार: पल्स, कैलिबर 8। पहली चेतावनी 1.8 सेकंड; फिर हर गोलीबारी के बीच {value0} सेकंड।|एकल गोलीबारी बारी-बारी से {value0} गोलियों के पंखे के आकार वाले फैलाव के साथ होती है।|जहाज़ की कहानी|वर्तमान उपकरण|संग्रह कार्ड · Cryptoid जगत की काल्पनिक कहानी / खेल के वास्तविक आँकड़े · संस्करण 01',
 bn: '৩টির মধ্যে {value0} তারা|উন্নয়ন · {value0}|যানের আবরণ সুরক্ষা প্রতি জীবনে শত্রুর প্রক্ষেপণের {value0}টি আঘাত শোষণ করে। এটি যানের সরাসরি সংঘর্ষ থেকে রক্ষা করে না।|কেন্দ্রীয় অস্ত্র: পালস, ক্যালিবার ৮। প্রথম সতর্কতা ১.৮ সেকেন্ড; এরপর প্রতিটি গুলিবর্ষণের মধ্যে {value0} সেকেন্ড।|একক গুলির সঙ্গে {value0}টি গুলির পাখার মতো ছড়ানো গুলি পর্যায়ক্রমে চলে।|যানের গল্প|বর্তমান সরঞ্জাম|সংগ্রহের কার্ড · Cryptoid জগতের কাল্পনিক গল্প / খেলার প্রকৃত পরিসংখ্যান · সংস্করণ ০১',
 ar: '{value0} من 3 نجوم|ترقية · {value0}|تمتص حماية الهيكل {value0} إصابات بمقذوفات العدو لكل حياة. ولا تحمي من الاصطدام المباشر بين السفن.|السلاح المركزي: نبضي، عيار 8. التحذير الأول 1.8 ثانية؛ ثم {value0} ثانية بين الرشقات.|تتناوب الطلقات الفردية مع انتشار مروحي من {value0} طلقات.|قصة السفينة|التجهيزات الحالية|بطاقة مقتنيات · قصة خيالية من عالم Cryptoid / إحصاءات اللعبة الفعلية · الإصدار 01',
 ur: '3 میں سے {value0} ستارے|اپ گریڈ · {value0}|جہاز کا حفاظتی خول ہر جان میں دشمن کے گولوں کی {value0} ضربیں جذب کرتا ہے۔ یہ جہازوں کے براہ راست تصادم سے نہیں بچاتا۔|مرکزی ہتھیار: پلس، کیلیبر 8۔ پہلی تنبیہ 1.8 سیکنڈ؛ پھر فائر کے سلسلوں کے درمیان {value0} سیکنڈ۔|ایک گولی کے فائر اور {value0} گولیوں کے پنکھے نما پھیلاؤ باری باری آتے ہیں۔|جہاز کی کہانی|موجودہ سازوسامان|مجموعے کا کارڈ · Cryptoid کی دنیا کی فرضی کہانی / کھیل کے حقیقی اعدادوشمار · ایڈیشن 01',
 fa: '{value0} از 3 ستاره|ارتقا · {value0}|محافظ بدنه در هر جان {value0} برخورد پرتابهٔ دشمن را جذب می‌کند. در برابر برخورد مستقیم سفینه‌ها محافظت نمی‌کند.|سلاح مرکزی: پالسی، کالیبر 8. هشدار اول 1.8 ثانیه؛ سپس {value0} ثانیه فاصله بین رگبارها.|شلیک‌های تکی با بادبزن‌های {value0} تیر به‌تناوب انجام می‌شوند.|داستان سفینه|تجهیزات فعلی|کارت مجموعه · داستانی تخیلی از جهان Cryptoid / آمار واقعی بازی · نسخهٔ 01',
 fil: '{value0} sa 3 bituin|Pag-upgrade · {value0}|Sinisipsip ng proteksiyon ng katawan ang {value0} tama ng bala ng kaaway bawat buhay. Hindi ito pananggalang sa direktang banggaan ng mga barko.|Gitnang sandata: pulse, kalibre 8. Unang babala: 1.8 segundo; pagkatapos ay {value0} segundo sa pagitan ng mga sunod-sunod na putok.|Nagsasalitan ang iisang putok at mga abaniko ng {value0} putok.|KUWENTO NG BARKO|KASALUKUYANG KAGAMITAN|KOLEKSIYONG KARD · Kathang-isip sa mundo ng Cryptoid / aktuwal na estadistika ng laro · Edisyon 01',
 sw: '{value0} kati ya nyota 3|Uboreshaji · {value0}|Ulinzi wa mwili hufyonza mapigo {value0} ya makombora ya adui kwa kila maisha. Haulindi dhidi ya migongano ya moja kwa moja ya meli.|Silaha ya kati: mpigo, kaliba 8. Onyo la kwanza sekunde 1.8; kisha sekunde {value0} kati ya mfululizo wa risasi.|Risasi moja hubadilishana na risasi {value0} zilizotawanywa kama feni.|HADITHI YA MELI|VIFAA VYA SASA|KADI YA MKUSANYIKO · Hadithi ya kubuni ya ulimwengu wa Cryptoid / takwimu halisi za mchezo · Toleo 01',
};
export const collectionEquipmentTranslations: Partial<Record<Locale, Record<string, string>>> = {};
for (const [locale, row] of Object.entries(rows)) {
 const values=row.split('|');
 if(values.length!==collectionEquipmentKeys.length)throw new Error(`Invalid collection equipment row: ${locale}`);
 collectionEquipmentTranslations[locale as Locale]=Object.fromEntries(collectionEquipmentKeys.map((key,index)=>[key,values[index]]));
}
