const keys = [
  'Open the side Weapons tab to choose equipment. Closing it resumes the mission after 3–2–1.',
  'When a timed weapon expires, the strongest enabled weapon takes over; otherwise the standard laser. Auto-reload uses owned charges without pausing.',
  'Free boosts can appear throughout the campaign, but each type appears only once per level.',
] as const;

const rows: Record<string, readonly [string, string, string]> = {
  de: ['Öffne den seitlichen Tab „Waffen“, um Ausrüstung zu wählen. Nach dem Schließen läuft die Mission nach 3–2–1 weiter.', 'Wenn eine zeitbegrenzte Waffe ausläuft, übernimmt die stärkste aktivierte Waffe, sonst der Standardlaser. Auto-Reload nutzt vorhandene Ladungen ohne Pause.', 'Kostenlose Power-ups erscheinen während der ganzen Kampagne, aber jeder Typ nur einmal pro Level.'],
  es: ['Abre la pestaña lateral Armas para elegir equipo. Al cerrarla, la misión continúa tras 3–2–1.', 'Cuando se agota un arma temporal, se usa la más potente activada; si no hay otra, el láser estándar. La recarga automática usa cargas propias sin pausar.', 'Los potenciadores gratuitos pueden aparecer durante toda la campaña, pero cada tipo solo una vez por nivel.'],
  fr: ['Ouvre l’onglet latéral Armes pour choisir ton équipement. Après sa fermeture, la mission reprend après 3–2–1.', 'Quand une arme temporaire expire, l’arme activée la plus puissante prend le relais, sinon le laser standard. La recharge auto utilise les charges possédées sans pause.', 'Des bonus gratuits peuvent apparaître tout au long de la campagne, mais chaque type une seule fois par niveau.'],
  pt: ['Abre o separador lateral Armas para escolher equipamento. Ao fechá-lo, a missão retoma após 3–2–1.', 'Quando uma arma temporária acaba, assume a arma ativa mais forte; caso contrário, o laser padrão. A recarga automática usa cargas existentes sem pausar.', 'Os reforços gratuitos podem surgir durante toda a campanha, mas cada tipo apenas uma vez por nível.'],
  it: ['Apri la scheda laterale Armi per scegliere l’equipaggiamento. Chiudendola, la missione riprende dopo 3–2–1.', 'Quando un’arma temporanea scade, subentra l’arma attivata più potente, altrimenti il laser standard. La ricarica automatica usa cariche possedute senza pausa.', 'I potenziamenti gratuiti possono apparire durante la campagna, ma ogni tipo solo una volta per livello.'],
  pl: ['Otwórz boczną kartę Broń, aby wybrać wyposażenie. Po zamknięciu misja wznowi się po 3–2–1.', 'Po wygaśnięciu broni czasowej włącza się najsilniejsza aktywna broń, a jeśli jej nie ma, standardowy laser. Autoładowanie zużywa posiadane ładunki bez pauzy.', 'Darmowe ulepszenia pojawiają się przez całą kampanię, ale każdy rodzaj tylko raz na poziom.'],
  tr: ['Ekipman seçmek için yandaki Silahlar sekmesini aç. Kapatınca görev 3–2–1 sonrası devam eder.', 'Süreli silah bittiğinde en güçlü etkin silah devreye girer; yoksa standart lazer kullanılır. Otomatik doldurma mevcut şarjları oyunu durdurmadan kullanır.', 'Ücretsiz güçlendirmeler sefer boyunca çıkabilir, ancak her tür bir seviyede yalnızca bir kez görünür.'],
  ru: ['Откройте боковую вкладку «Оружие», чтобы выбрать снаряжение. После закрытия миссия продолжится через 3–2–1.', 'Когда срок оружия истекает, включается самое мощное активное оружие, иначе стандартный лазер. Автоперезарядка использует имеющиеся заряды без паузы.', 'Бесплатные усиления встречаются всю кампанию, но каждый тип только один раз за уровень.'],
  hr: ['Otvori bočnu karticu Oružja za odabir opreme. Nakon zatvaranja misija se nastavlja poslije 3–2–1.', 'Kad vremenski ograničeno oružje istekne, preuzima najjače aktivno oružje, inače osnovni laser. Automatsko punjenje troši postojeća punjenja bez pauze.', 'Besplatna pojačanja mogu se pojavljivati cijelu kampanju, ali svaka vrsta samo jednom po razini.'],
  cs: ['Otevři boční kartu Zbraně a vyber vybavení. Po zavření bude mise pokračovat po 3–2–1.', 'Když časovaná zbraň vyprší, převezme ji nejsilnější aktivní zbraň, jinak základní laser. Automatické nabití používá vlastní náboje bez pozastavení.', 'Bezplatná posílení se mohou objevit během celé kampaně, ale každý typ jen jednou za úroveň.'],
  sk: ['Otvor bočnú kartu Zbrane a vyber vybavenie. Po zatvorení bude misia pokračovať po 3–2–1.', 'Keď časovaná zbraň vyprší, prevezme ju najsilnejšia aktívna zbraň, inak základný laser. Automatické nabitie používa vlastné náboje bez pozastavenia.', 'Bezplatné posilnenia sa môžu objaviť počas celej kampane, ale každý typ len raz za úroveň.'],
  hu: ['Nyisd meg az oldalsó Fegyverek fület a felszerelés kiválasztásához. Bezárás után a küldetés 3–2–1 után folytatódik.', 'Ha lejár egy időzített fegyver, a legerősebb bekapcsolt fegyver lép a helyére, különben az alaplézer. Az automatikus újratöltés saját tölteteket használ szünet nélkül.', 'Ingyenes erősítések a kampány során végig megjelenhetnek, de egy típus szintenként csak egyszer.'],
  ro: ['Deschide fila laterală Arme pentru a alege echipamentul. După închidere, misiunea reia după 3–2–1.', 'Când expiră o armă temporară, intră în funcțiune cea mai puternică armă activată sau laserul standard. Reîncărcarea automată folosește încărcături deținute fără pauză.', 'Bonusurile gratuite pot apărea în toată campania, dar fiecare tip o singură dată pe nivel.'],
  sr: ['Отвори бочну картицу Оружје да изабереш опрему. После затварања мисија се наставља након 3–2–1.', 'Кад временски ограничено оружје истекне, преузима најјаче активно оружје, иначе стандардни ласер. Аутоматско пуњење користи постојећа пуњења без паузе.', 'Бесплатна појачања могу се појављивати током кампање, али свака врста само једном по нивоу.'],
  uk: ['Відкрийте бічну вкладку «Зброя», щоб вибрати спорядження. Після закриття місія продовжиться через 3–2–1.', 'Коли час зброї спливає, її замінює найпотужніша активна зброя або стандартний лазер. Автоперезаряджання використовує наявні заряди без паузи.', 'Безкоштовні підсилення можуть з’являтися протягом усієї кампанії, але кожен тип лише раз на рівень.'],
  th: ['เปิดแท็บอาวุธด้านข้างเพื่อเลือกอุปกรณ์ เมื่อปิดแล้วภารกิจจะดำเนินต่อหลังนับ 3–2–1', 'เมื่ออาวุธจำกัดเวลาหมดลง ระบบจะเปลี่ยนไปใช้อาวุธที่เปิดใช้งานและแรงที่สุด หรือเลเซอร์มาตรฐาน การบรรจุอัตโนมัติใช้กระสุนที่มีโดยไม่หยุดเกม', 'ไอเทมเสริมฟรีอาจปรากฏตลอดแคมเปญ แต่แต่ละชนิดจะปรากฏเพียงครั้งเดียวต่อด่าน'],
};

export const package2Translations: Record<string, Record<string, string>> = Object.fromEntries(
  Object.entries(rows).map(([locale, values]) => [locale, Object.fromEntries(keys.map((key, i) => [key, values[i]]))]),
);
