// Hand-written control labels. Full UI/lore coverage is gated separately.
import type { Locale } from './config.ts';
export const regionalCoreKeys = [
  'Play', 'Back', 'Close', 'Retry', 'Resume', 'Pause', 'New game', 'Home',
  'Language', 'Current language', 'Automatic (device language)', 'Change',
  'Settings', 'SYSTEM / SETTINGS', 'All settings', 'Quick access',
  'Ships', 'Weapons', 'Power-ups', 'Progress', 'Rewards', 'Score', 'Level', 'Block',
  'Shop', 'Shop / Hangar', 'Hangar', 'Collection & ranks', 'Your collection',
  'Sign in with Pi', 'Sign out', 'Signed in as', 'Signing in…',
  'Full screen', 'Music volume', 'Effects volume', 'Music & effects',
  'Music on', 'Music off', 'Enable sound', 'Controls', 'Display',
  'Right-handed controls', 'Left-handed controls', 'Above finger', 'Under finger',
  'Touch sensitivity', 'Control area', 'Gentle', 'Normal', 'Fast', 'Compact', 'Wide',
  'Owned', 'Not owned', 'EQUIPPED', 'Available', 'Locked', 'Buy for',
  'STANDARD', 'ADVANCED', 'ELITE', 'MAINNET READY', 'Career Score', 'Best Run',
  'Run level', 'Profile level', 'Service rank', 'Player', 'Hearts', 'Shield',
  'Weapon level', 'Active weapon', 'Quantity', 'Charges', 'Auto-reload', 'On', 'Off',
  'Back to game', 'Game Over', 'Victory', 'MISSION PAUSED', 'MISSION FAILED',
  'Game guide', 'How to Play', 'Privacy policy', 'Terms of service', 'Account & legal',
  'Admin center', 'Loading admin center…', 'Saving game…', 'Saved to your Pi account.',
  'Continue', 'Categories', 'Boss', 'Bosses', 'The story', 'Current equipment',
  'COLLECTOR CARD RECEIVED', 'Enable card sound', 'Open card', 'Save PNG',
  'Previous', 'Next', 'Loading collection …', 'Could not load your collection.',
  'UNLOCKED', 'Unlimited', 'Remaining time', 'Not in stock',
] as const;
const rows: Partial<Record<Locale, string>> = {
zh: `开始|返回|关闭|重试|继续|暂停|新游戏|主页|语言|当前语言|自动（设备语言）|更改|设置|系统／设置|全部设置|快捷菜单|飞船|武器|强化道具|进度|奖励|得分|关卡|区块|商店|商店／机库|机库|收藏与军衔|你的收藏|使用 Pi 登录|退出登录|已登录为|正在登录…|全屏|音乐音量|音效音量|音乐与音效|音乐开启|音乐关闭|开启声音|操作|显示|右手操作|左手操作|手指上方|手指下方|触控灵敏度|操作区域|柔和|正常|快速|紧凑|宽广|已拥有|未拥有|已装备|可用|已锁定|购买价格|标准|高级|精英|主网就绪|生涯总分|单局最高分|单局关卡|账号关卡|军衔|玩家|生命|护盾|武器等级|当前武器|数量|充能次数|自动装填|开启|关闭|返回游戏|游戏结束|胜利|任务已暂停|任务失败|游戏指南|玩法说明|隐私政策|服务条款|账号与法律|管理中心|正在加载管理中心…|正在保存游戏…|已保存到你的 Pi 账号。|继续|分类|首领|首领|故事|当前装备|已获得收藏卡|开启卡片音效|打开卡片|保存 PNG|上一张|下一张|正在加载收藏…|无法加载你的收藏。|已解锁|无限|剩余时间|无库存`,
vi: `Chơi|Quay lại|Đóng|Thử lại|Tiếp tục|Tạm dừng|Trò chơi mới|Trang chủ|Ngôn ngữ|Ngôn ngữ hiện tại|Tự động (ngôn ngữ thiết bị)|Thay đổi|Cài đặt|HỆ THỐNG / CÀI ĐẶT|Tất cả cài đặt|Truy cập nhanh|Tàu|Vũ khí|Vật phẩm tăng sức mạnh|Tiến độ|Phần thưởng|Điểm|Cấp độ|Khối|Cửa hàng|Cửa hàng / Nhà chứa|Nhà chứa|Bộ sưu tập & cấp bậc|Bộ sưu tập của bạn|Đăng nhập bằng Pi|Đăng xuất|Đã đăng nhập với|Đang đăng nhập…|Toàn màn hình|Âm lượng nhạc|Âm lượng hiệu ứng|Nhạc & hiệu ứng|Bật nhạc|Tắt nhạc|Bật âm thanh|Điều khiển|Hiển thị|Điều khiển tay phải|Điều khiển tay trái|Trên ngón tay|Dưới ngón tay|Độ nhạy cảm ứng|Vùng điều khiển|Nhẹ|Bình thường|Nhanh|Gọn|Rộng|Đã sở hữu|Chưa sở hữu|ĐÃ TRANG BỊ|Có sẵn|Đã khóa|Mua với|TIÊU CHUẨN|NÂNG CAO|TINH ANH|SẴN SÀNG MAINNET|Tổng điểm sự nghiệp|Lượt chơi tốt nhất|Cấp độ lượt chơi|Cấp độ hồ sơ|Cấp bậc|Người chơi|Mạng|Lá chắn|Cấp vũ khí|Vũ khí hiện tại|Số lượng|Lượt nạp|Tự nạp lại|Bật|Tắt|Về trò chơi|Trò chơi kết thúc|Chiến thắng|NHIỆM VỤ TẠM DỪNG|NHIỆM VỤ THẤT BẠI|Hướng dẫn trò chơi|Cách chơi|Chính sách riêng tư|Điều khoản dịch vụ|Tài khoản & pháp lý|Trung tâm quản trị|Đang tải quản trị…|Đang lưu trò chơi…|Đã lưu vào tài khoản Pi.|Tiếp tục|Danh mục|Trùm|Các trùm|Câu chuyện|Trang bị hiện tại|ĐÃ NHẬN THẺ SƯU TẦM|Bật âm thanh thẻ|Mở thẻ|Lưu PNG|Trước|Sau|Đang tải bộ sưu tập…|Không thể tải bộ sưu tập.|ĐÃ MỞ KHÓA|Không giới hạn|Thời gian còn lại|Hết hàng`,
id: `Main|Kembali|Tutup|Coba lagi|Lanjutkan|Jeda|Permainan baru|Beranda|Bahasa|Bahasa saat ini|Otomatis (bahasa perangkat)|Ubah|Pengaturan|SISTEM / PENGATURAN|Semua pengaturan|Akses cepat|Kapal|Senjata|Peningkat daya|Progres|Hadiah|Skor|Level|Blok|Toko|Toko / Hanggar|Hanggar|Koleksi & pangkat|Koleksi Anda|Masuk dengan Pi|Keluar|Masuk sebagai|Sedang masuk…|Layar penuh|Volume musik|Volume efek|Musik & efek|Musik aktif|Musik nonaktif|Aktifkan suara|Kontrol|Tampilan|Kontrol tangan kanan|Kontrol tangan kiri|Di atas jari|Di bawah jari|Sensitivitas sentuhan|Area kontrol|Lembut|Normal|Cepat|Ringkas|Lebar|Dimiliki|Belum dimiliki|DIPASANG|Tersedia|Terkunci|Beli dengan|STANDAR|LANJUTAN|ELITE|SIAP MAINNET|Skor karier|Permainan terbaik|Level permainan|Level profil|Pangkat|Pemain|Nyawa|Perisai|Level senjata|Senjata aktif|Jumlah|Muatan|Isi ulang otomatis|Aktif|Nonaktif|Kembali ke permainan|Permainan berakhir|Kemenangan|MISI DIJEDA|MISI GAGAL|Panduan permainan|Cara bermain|Kebijakan privasi|Ketentuan layanan|Akun & hukum|Pusat admin|Memuat pusat admin…|Menyimpan permainan…|Tersimpan di akun Pi Anda.|Lanjutkan|Kategori|Bos|Para bos|Cerita|Perlengkapan saat ini|KARTU KOLEKSI DITERIMA|Aktifkan suara kartu|Buka kartu|Simpan PNG|Sebelumnya|Berikutnya|Memuat koleksi…|Tidak dapat memuat koleksi.|TERBUKA|Tak terbatas|Sisa waktu|Stok habis`,
ko: `플레이|뒤로|닫기|다시 시도|계속|일시 정지|새 게임|홈|언어|현재 언어|자동 (기기 언어)|변경|설정|시스템 / 설정|모든 설정|빠른 메뉴|함선|무기|강화 아이템|진행 상황|보상|점수|레벨|블록|상점|상점 / 격납고|격납고|컬렉션 및 계급|내 컬렉션|Pi로 로그인|로그아웃|로그인 계정|로그인 중…|전체 화면|음악 음량|효과음 음량|음악 및 효과음|음악 켜짐|음악 꺼짐|소리 켜기|조작|화면|오른손 조작|왼손 조작|손가락 위|손가락 아래|터치 감도|조작 영역|부드럽게|보통|빠르게|좁게|넓게|보유|미보유|장착됨|사용 가능|잠김|구매 가격|일반|고급|엘리트|메인넷 준비|누적 점수|최고 기록|게임 레벨|프로필 레벨|계급|플레이어|목숨|보호막|무기 레벨|사용 중인 무기|수량|충전 횟수|자동 재장전|켜짐|꺼짐|게임으로 돌아가기|게임 오버|승리|임무 일시 정지|임무 실패|게임 안내|플레이 방법|개인정보 처리방침|서비스 약관|계정 및 법률|관리 센터|관리 센터 로딩 중…|게임 저장 중…|Pi 계정에 저장되었습니다.|계속|분류|보스|보스|이야기|현재 장비|수집 카드 획득|카드 소리 켜기|카드 열기|PNG 저장|이전|다음|컬렉션 로딩 중…|컬렉션을 불러올 수 없습니다.|잠금 해제|무제한|남은 시간|재고 없음`,
ja: `プレイ|戻る|閉じる|再試行|続ける|一時停止|新しいゲーム|ホーム|言語|現在の言語|自動（端末の言語）|変更|設定|システム／設定|すべての設定|クイックメニュー|宇宙船|武器|強化アイテム|進行状況|報酬|スコア|レベル|ブロック|ショップ|ショップ／格納庫|格納庫|コレクションと階級|あなたのコレクション|Piでログイン|ログアウト|ログイン中のユーザー|ログイン中…|全画面|音楽の音量|効果音の音量|音楽と効果音|音楽オン|音楽オフ|音を有効にする|操作|表示|右手操作|左手操作|指の上|指の下|タッチ感度|操作エリア|穏やか|標準|速い|狭い|広い|所有済み|未所有|装備中|利用可能|ロック中|購入価格|標準|上級|エリート|メインネット準備完了|累計スコア|最高記録|プレイのレベル|プロフィールレベル|階級|プレイヤー|ライフ|シールド|武器レベル|現在の武器|数量|使用回数|自動リロード|オン|オフ|ゲームに戻る|ゲームオーバー|勝利|任務一時停止|任務失敗|ゲームガイド|遊び方|プライバシーポリシー|利用規約|アカウントと法務|管理センター|管理センターを読み込み中…|ゲームを保存中…|Piアカウントに保存しました。|続ける|カテゴリー|ボス|ボス|物語|現在の装備|コレクションカード獲得|カード音を有効にする|カードを開く|PNGを保存|前へ|次へ|コレクションを読み込み中…|コレクションを読み込めません。|解放済み|無制限|残り時間|在庫なし`,
hi: `खेलें|वापस|बंद करें|फिर कोशिश करें|जारी रखें|रोकें|नया खेल|मुखपृष्ठ|भाषा|वर्तमान भाषा|स्वचालित (डिवाइस की भाषा)|बदलें|सेटिंग्स|सिस्टम / सेटिंग्स|सभी सेटिंग्स|त्वरित पहुँच|यान|हथियार|पावर-अप|प्रगति|पुरस्कार|स्कोर|स्तर|ब्लॉक|दुकान|दुकान / हैंगर|हैंगर|संग्रह और रैंक|आपका संग्रह|Pi से साइन इन करें|साइन आउट|साइन इन किया है|साइन इन हो रहा है…|पूरी स्क्रीन|संगीत की आवाज़|ध्वनि प्रभाव की आवाज़|संगीत और प्रभाव|संगीत चालू|संगीत बंद|ध्वनि चालू करें|नियंत्रण|प्रदर्शन|दाएँ हाथ से नियंत्रण|बाएँ हाथ से नियंत्रण|उँगली के ऊपर|उँगली के नीचे|स्पर्श संवेदनशीलता|नियंत्रण क्षेत्र|हल्का|सामान्य|तेज़|छोटा|चौड़ा|स्वामित्व में|स्वामित्व में नहीं|सुसज्जित|उपलब्ध|बंद|खरीदें|मानक|उन्नत|एलीट|मेननेट के लिए तैयार|कुल करियर स्कोर|सर्वश्रेष्ठ खेल|खेल का स्तर|प्रोफ़ाइल स्तर|रैंक|खिलाड़ी|जीवन|ढाल|हथियार स्तर|सक्रिय हथियार|मात्रा|चार्ज|स्वचालित रीलोड|चालू|बंद|खेल पर वापस जाएँ|खेल समाप्त|जीत|मिशन रुका हुआ है|मिशन विफल|खेल गाइड|कैसे खेलें|गोपनीयता नीति|सेवा की शर्तें|खाता और कानूनी|व्यवस्थापक केंद्र|व्यवस्थापक केंद्र लोड हो रहा है…|खेल सहेजा जा रहा है…|आपके Pi खाते में सहेजा गया।|जारी रखें|श्रेणियाँ|बॉस|बॉस|कहानी|वर्तमान उपकरण|संग्रह कार्ड मिला|कार्ड की ध्वनि चालू करें|कार्ड खोलें|PNG सहेजें|पिछला|अगला|संग्रह लोड हो रहा है…|संग्रह लोड नहीं हो सका।|अनलॉक|असीमित|शेष समय|स्टॉक में नहीं`,
bn: `খেলুন|ফিরে যান|বন্ধ করুন|আবার চেষ্টা করুন|চালিয়ে যান|বিরতি|নতুন খেলা|হোম|ভাষা|বর্তমান ভাষা|স্বয়ংক্রিয় (ডিভাইসের ভাষা)|পরিবর্তন|সেটিংস|সিস্টেম / সেটিংস|সব সেটিংস|দ্রুত প্রবেশ|মহাকাশযান|অস্ত্র|পাওয়ার-আপ|অগ্রগতি|পুরস্কার|স্কোর|স্তর|ব্লক|দোকান|দোকান / হ্যাঙ্গার|হ্যাঙ্গার|সংগ্রহ ও পদমর্যাদা|আপনার সংগ্রহ|Pi দিয়ে সাইন ইন|সাইন আউট|সাইন ইন করেছেন|সাইন ইন হচ্ছে…|পূর্ণ পর্দা|সঙ্গীতের আওয়াজ|শব্দ প্রভাবের আওয়াজ|সঙ্গীত ও প্রভাব|সঙ্গীত চালু|সঙ্গীত বন্ধ|শব্দ চালু করুন|নিয়ন্ত্রণ|প্রদর্শন|ডান হাতে নিয়ন্ত্রণ|বাম হাতে নিয়ন্ত্রণ|আঙুলের উপরে|আঙুলের নিচে|স্পর্শ সংবেদনশীলতা|নিয়ন্ত্রণের ক্ষেত্র|মৃদু|স্বাভাবিক|দ্রুত|ছোট|প্রশস্ত|আপনার আছে|আপনার নেই|সজ্জিত|উপলব্ধ|লক করা|কিনুন|মানক|উন্নত|এলিট|মেইননেট প্রস্তুত|মোট ক্যারিয়ার স্কোর|সেরা খেলা|খেলার স্তর|প্রোফাইলের স্তর|পদমর্যাদা|খেলোয়াড়|জীবন|ঢাল|অস্ত্রের স্তর|সক্রিয় অস্ত্র|পরিমাণ|চার্জ|স্বয়ংক্রিয় রিলোড|চালু|বন্ধ|খেলায় ফিরুন|খেলা শেষ|জয়|মিশনে বিরতি|মিশন ব্যর্থ|খেলার নির্দেশিকা|কীভাবে খেলবেন|গোপনীয়তা নীতি|পরিষেবার শর্তাবলি|অ্যাকাউন্ট ও আইন|প্রশাসক কেন্দ্র|প্রশাসক কেন্দ্র লোড হচ্ছে…|খেলা সংরক্ষণ হচ্ছে…|আপনার Pi অ্যাকাউন্টে সংরক্ষিত।|চালিয়ে যান|বিভাগ|বস|বস|গল্প|বর্তমান সরঞ্জাম|সংগ্রহের কার্ড পাওয়া গেছে|কার্ডের শব্দ চালু করুন|কার্ড খুলুন|PNG সংরক্ষণ|আগের|পরের|সংগ্রহ লোড হচ্ছে…|সংগ্রহ লোড করা যায়নি।|আনলক|সীমাহীন|বাকি সময়|স্টকে নেই`,
ar: `العب|رجوع|إغلاق|أعد المحاولة|متابعة|إيقاف مؤقت|لعبة جديدة|الرئيسية|اللغة|اللغة الحالية|تلقائي (لغة الجهاز)|تغيير|الإعدادات|النظام / الإعدادات|كل الإعدادات|الوصول السريع|السفن|الأسلحة|التعزيزات|التقدم|المكافآت|النقاط|المستوى|الكتلة|المتجر|المتجر / الحظيرة|الحظيرة|المجموعة والرتب|مجموعتك|تسجيل الدخول باستخدام Pi|تسجيل الخروج|تم تسجيل الدخول باسم|جارٍ تسجيل الدخول…|ملء الشاشة|مستوى صوت الموسيقى|مستوى صوت المؤثرات|الموسيقى والمؤثرات|الموسيقى مفعلة|الموسيقى معطلة|تفعيل الصوت|التحكم|العرض|التحكم باليد اليمنى|التحكم باليد اليسرى|فوق الإصبع|تحت الإصبع|حساسية اللمس|منطقة التحكم|لطيف|عادي|سريع|صغير|واسع|مملوك|غير مملوك|مجهز|متاح|مقفل|شراء مقابل|قياسي|متقدم|نخبة|جاهز للشبكة الرئيسية|مجموع النقاط|أفضل جولة|مستوى الجولة|مستوى الملف الشخصي|الرتبة|اللاعب|الأرواح|الدرع|مستوى السلاح|السلاح النشط|الكمية|الشحنات|إعادة تلقيم تلقائية|تشغيل|إيقاف|العودة إلى اللعبة|انتهت اللعبة|انتصار|المهمة متوقفة|فشلت المهمة|دليل اللعبة|كيفية اللعب|سياسة الخصوصية|شروط الخدمة|الحساب والشؤون القانونية|مركز الإدارة|جارٍ تحميل مركز الإدارة…|جارٍ حفظ اللعبة…|تم الحفظ في حساب Pi.|متابعة|الفئات|الزعيم|الزعماء|القصة|المعدات الحالية|تم استلام بطاقة المجموعة|تفعيل صوت البطاقة|فتح البطاقة|حفظ PNG|السابق|التالي|جارٍ تحميل المجموعة…|تعذر تحميل مجموعتك.|مفتوح|غير محدود|الوقت المتبقي|غير متوفر`,
ur: `کھیلیں|واپس|بند کریں|دوبارہ کوشش کریں|جاری رکھیں|وقفہ|نیا کھیل|مرکزی صفحہ|زبان|موجودہ زبان|خودکار (آلے کی زبان)|تبدیل کریں|ترتیبات|نظام / ترتیبات|تمام ترتیبات|فوری رسائی|جہاز|ہتھیار|پاور اپس|پیش رفت|انعامات|اسکور|مرحلہ|بلاک|دکان|دکان / ہینگر|ہینگر|مجموعہ اور رینک|آپ کا مجموعہ|Pi سے سائن ان|سائن آؤٹ|سائن ان ہے|سائن ان ہو رہا ہے…|پوری اسکرین|موسیقی کی آواز|اثرات کی آواز|موسیقی اور اثرات|موسیقی جاری|موسیقی بند|آواز فعال کریں|کنٹرول|ڈسپلے|دائیں ہاتھ کا کنٹرول|بائیں ہاتھ کا کنٹرول|انگلی کے اوپر|انگلی کے نیچے|لمس کی حساسیت|کنٹرول کا علاقہ|نرم|عام|تیز|مختصر|وسیع|ملکیت میں|ملکیت میں نہیں|لیس|دستیاب|مقفل|خریدیں|معیاری|اعلیٰ|ایلیٹ|مین نیٹ کے لیے تیار|کل کیریئر اسکور|بہترین کھیل|کھیل کا مرحلہ|پروفائل کا مرحلہ|رینک|کھلاڑی|جانیں|ڈھال|ہتھیار کا درجہ|فعال ہتھیار|مقدار|چارجز|خودکار ری لوڈ|جاری|بند|کھیل پر واپس|کھیل ختم|فتح|مشن موقوف|مشن ناکام|کھیل کی رہنمائی|کھیلنے کا طریقہ|رازداری کی پالیسی|خدمت کی شرائط|اکاؤنٹ اور قانونی|منتظم مرکز|منتظم مرکز لوڈ ہو رہا ہے…|کھیل محفوظ ہو رہا ہے…|آپ کے Pi اکاؤنٹ میں محفوظ ہوگیا۔|جاری رکھیں|زمرے|باس|باس|کہانی|موجودہ سامان|مجموعے کا کارڈ موصول|کارڈ کی آواز فعال کریں|کارڈ کھولیں|PNG محفوظ کریں|پچھلا|اگلا|مجموعہ لوڈ ہو رہا ہے…|آپ کا مجموعہ لوڈ نہیں ہو سکا۔|کھلا|لامحدود|باقی وقت|اسٹاک میں نہیں`,
fa: `بازی|بازگشت|بستن|تلاش دوباره|ادامه|توقف موقت|بازی جدید|خانه|زبان|زبان فعلی|خودکار (زبان دستگاه)|تغییر|تنظیمات|سیستم / تنظیمات|همه تنظیمات|دسترسی سریع|سفینه‌ها|سلاح‌ها|تقویت‌کننده‌ها|پیشرفت|پاداش‌ها|امتیاز|مرحله|بلوک|فروشگاه|فروشگاه / آشیانه|آشیانه|مجموعه و درجه‌ها|مجموعه شما|ورود با Pi|خروج|وارد شده به نام|در حال ورود…|تمام‌صفحه|صدای موسیقی|صدای جلوه‌ها|موسیقی و جلوه‌ها|موسیقی روشن|موسیقی خاموش|فعال کردن صدا|کنترل|نمایش|کنترل راست‌دست|کنترل چپ‌دست|بالای انگشت|زیر انگشت|حساسیت لمس|محدوده کنترل|ملایم|عادی|سریع|فشرده|گسترده|در اختیار|در اختیار نیست|مجهز|در دسترس|قفل|خرید با|استاندارد|پیشرفته|نخبه|آماده مین‌نت|امتیاز کل|بهترین بازی|مرحله بازی|مرحله پروفایل|درجه|بازیکن|جان‌ها|سپر|سطح سلاح|سلاح فعال|تعداد|شارژها|بارگذاری خودکار|روشن|خاموش|بازگشت به بازی|پایان بازی|پیروزی|مأموریت متوقف|مأموریت ناموفق|راهنمای بازی|روش بازی|سیاست حریم خصوصی|شرایط خدمات|حساب و امور حقوقی|مرکز مدیریت|در حال بارگیری مدیریت…|در حال ذخیره بازی…|در حساب Pi شما ذخیره شد.|ادامه|دسته‌ها|باس|باس‌ها|داستان|تجهیزات فعلی|کارت مجموعه دریافت شد|فعال کردن صدای کارت|باز کردن کارت|ذخیره PNG|قبلی|بعدی|در حال بارگیری مجموعه…|مجموعه بارگیری نشد.|باز شده|نامحدود|زمان باقی‌مانده|ناموجود`,
fil: `Maglaro|Bumalik|Isara|Subukan muli|Magpatuloy|I-pause|Bagong laro|Home|Wika|Kasalukuyang wika|Awtomatiko (wika ng device)|Baguhin|Mga setting|SYSTEM / MGA SETTING|Lahat ng setting|Mabilis na pag-access|Mga barko|Mga sandata|Mga power-up|Progreso|Mga gantimpala|Iskor|Antas|Bloke|Tindahan|Tindahan / Hangar|Hangar|Koleksiyon at ranggo|Iyong koleksiyon|Mag-sign in gamit ang Pi|Mag-sign out|Naka-sign in bilang|Nagsa-sign in…|Buong screen|Lakas ng musika|Lakas ng effects|Musika at effects|Musika naka-on|Musika naka-off|Paganahin ang tunog|Mga kontrol|Display|Kontrol sa kanang kamay|Kontrol sa kaliwang kamay|Sa ibabaw ng daliri|Sa ilalim ng daliri|Sensitivity ng touch|Lugar ng kontrol|Banayad|Normal|Mabilis|Maliit|Malawak|Pag-aari|Hindi pag-aari|NAKA-EQUIP|Available|Naka-lock|Bilhin sa|STANDARD|ADVANCED|ELITE|HANDA SA MAINNET|Kabuuang iskor|Pinakamahusay na laro|Antas ng laro|Antas ng profile|Ranggo|Manlalaro|Buhay|Kalasag|Antas ng sandata|Aktibong sandata|Dami|Mga charge|Awtomatikong reload|On|Off|Bumalik sa laro|Tapos na ang laro|Tagumpay|NAKA-PAUSE ANG MISYON|BIGONG MISYON|Gabay sa laro|Paano maglaro|Patakaran sa privacy|Mga tuntunin ng serbisyo|Account at legal|Admin center|Nilo-load ang admin center…|Sine-save ang laro…|Na-save sa iyong Pi account.|Magpatuloy|Mga kategorya|Boss|Mga boss|Ang kuwento|Kasalukuyang kagamitan|NATANGGAP ANG COLLECTOR CARD|Paganahin ang tunog ng card|Buksan ang card|I-save ang PNG|Nakaraan|Susunod|Nilo-load ang koleksiyon…|Hindi ma-load ang koleksiyon.|NA-UNLOCK|Walang limitasyon|Natitirang oras|Wala sa stock`,
sw: `Cheza|Rudi|Funga|Jaribu tena|Endelea|Sitisha|Mchezo mpya|Mwanzo|Lugha|Lugha ya sasa|Otomatiki (lugha ya kifaa)|Badilisha|Mipangilio|MFUMO / MIPANGILIO|Mipangilio yote|Ufikiaji wa haraka|Meli|Silaha|Viongeza nguvu|Maendeleo|Zawadi|Alama|Kiwango|Kizuizi|Duka|Duka / Hangari|Hangari|Mkusanyiko na vyeo|Mkusanyiko wako|Ingia kwa Pi|Toka|Umeingia kama|Inaingia…|Skrini nzima|Sauti ya muziki|Sauti ya athari|Muziki na athari|Muziki umewashwa|Muziki umezimwa|Washa sauti|Udhibiti|Onyesho|Udhibiti wa mkono wa kulia|Udhibiti wa mkono wa kushoto|Juu ya kidole|Chini ya kidole|Unyeti wa mguso|Eneo la udhibiti|Taratibu|Kawaida|Haraka|Finyu|Pana|Unamiliki|Huumiliki|IMEWEKEWA|Inapatikana|Imefungwa|Nunua kwa|KAWAIDA|YA JUU|BORA|TAYARI KWA MAINNET|Jumla ya alama|Mchezo bora|Kiwango cha mchezo|Kiwango cha wasifu|Cheo|Mchezaji|Maisha|Ngao|Kiwango cha silaha|Silaha hai|Idadi|Chaji|Kupakia upya kiotomatiki|Washa|Zima|Rudi kwenye mchezo|Mchezo umeisha|Ushindi|MISHENI IMESITISHWA|MISHENI IMESHINDWA|Mwongozo wa mchezo|Jinsi ya kucheza|Sera ya faragha|Masharti ya huduma|Akaunti na sheria|Kituo cha msimamizi|Inapakia kituo cha msimamizi…|Inahifadhi mchezo…|Imehifadhiwa kwenye akaunti yako ya Pi.|Endelea|Makundi|Bosi|Mabosi|Hadithi|Vifaa vya sasa|KADI YA MKUSANYIKO IMEPOKELEWA|Washa sauti ya kadi|Fungua kadi|Hifadhi PNG|Iliyotangulia|Inayofuata|Inapakia mkusanyiko…|Imeshindwa kupakia mkusanyiko.|IMEFUNGULIWA|Bila kikomo|Muda uliobaki|Haipo kwenye akiba`,
};
export const regionalTranslations: Partial<Record<Locale, Record<string, string>>> = {};
for (const [locale, text] of Object.entries(rows)) {
  const values = text.split('|');
  if (values.length !== regionalCoreKeys.length) throw new Error(`Regional row length: ${locale} (${values.length}/${regionalCoreKeys.length})`);
  regionalTranslations[locale as Locale] = Object.fromEntries(regionalCoreKeys.map((key, index) => [key, values[index]]));
}
export const regionalLocales = Object.keys(rows) as Locale[];
