export const hangarCatalog = [
  { id: "weapon_twin", kind: "weapon", name: "Twin Laser", description: "1 minute per charge", pricePi: 0.1, level: 2 },
  { id: "weapon_rapid_twin", kind: "weapon", name: "Rapid Twin", description: "1 minute per charge", pricePi: 0.16, level: 3 },
  { id: "weapon_triple", kind: "weapon", name: "Triple Laser", description: "1 minute per charge", pricePi: 0.22, level: 4 },
  { id: "weapon_plasma", kind: "weapon", name: "Plasma", description: "1 minute per charge", pricePi: 0.3, level: 5 },
  { id: "start_shield", kind: "power", name: "Start Shield", description: "Continuous protection for 60 seconds after activation. The timer pauses during mission transitions.", pricePi: 0.08, powerUp: "shield" },
  { id: "start_rapid", kind: "power", name: "Start Rapid Fire", description: "Activate faster automatic fire from the screen-edge icon for 60 seconds.", pricePi: 0.09, powerUp: "rapid" },
  { id: "start_overdrive", kind: "power", name: "Start Overdrive", description: "Activate stronger shots from the screen-edge icon for 60 seconds.", pricePi: 0.12, powerUp: "overdrive" },
  { id: "start_bomb", kind: "power", name: "Nova Bomb", description: "One use per mission. Destroys visible enemies and hostile shots. Damages boss turrets first; later turrets withstand more damage. The exposed boss hull survives the blast.", pricePi: 0.18, powerUp: "bomb" },
  { id: "start_emp", kind: "power", name: "EMP Pulse", description: "One use per mission. Disables enemy and boss weapons for 7 seconds. Ships and existing shots keep moving; EMP deals no damage.", pricePi: 0.14, powerUp: "emp" },
  { id: "armor_hull_mk1", kind: "armor", name: "Reinforced Hull", description: "Permanent armor: +1 heart at the start of every mission. No shield needed.", pricePi: 19.9, bonusHearts: 1 },
  { id: "armor_hull_mk2", kind: "armor", name: "Titanium Plating", description: "Permanent armor: +2 more hearts at the start of every mission. Stacks with Reinforced Hull.", pricePi: 29.9, bonusHearts: 2 },

  // Ship evolution upgrades are Pi purchases. Stage 1 hulls remain Shard purchases.
  { id: "ship_01_stage_2", kind: "ship_upgrade", name: "Ship 01 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 0, stage: 2 },
  { id: "ship_01_stage_3", kind: "ship_upgrade", name: "Ship 01 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 0, stage: 3 },
  { id: "ship_02_stage_2", kind: "ship_upgrade", name: "Ship 02 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 1, stage: 2 },
  { id: "ship_02_stage_3", kind: "ship_upgrade", name: "Ship 02 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 1, stage: 3 },
  { id: "ship_03_stage_2", kind: "ship_upgrade", name: "Ship 03 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 2, stage: 2 },
  { id: "ship_03_stage_3", kind: "ship_upgrade", name: "Ship 03 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 2, stage: 3 },
  { id: "ship_04_stage_2", kind: "ship_upgrade", name: "Ship 04 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 3, stage: 2 },
  { id: "ship_04_stage_3", kind: "ship_upgrade", name: "Ship 04 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 3, stage: 3 },
  { id: "ship_05_stage_2", kind: "ship_upgrade", name: "Ship 05 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 4, stage: 2 },
  { id: "ship_05_stage_3", kind: "ship_upgrade", name: "Ship 05 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 4, stage: 3 },
  { id: "ship_06_stage_2", kind: "ship_upgrade", name: "Ship 06 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 5, stage: 2 },
  { id: "ship_06_stage_3", kind: "ship_upgrade", name: "Ship 06 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 5, stage: 3 },
  { id: "ship_07_stage_2", kind: "ship_upgrade", name: "Ship 07 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 6, stage: 2 },
  { id: "ship_07_stage_3", kind: "ship_upgrade", name: "Ship 07 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 6, stage: 3 },
  { id: "ship_08_stage_2", kind: "ship_upgrade", name: "Ship 08 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 7, stage: 2 },
  { id: "ship_08_stage_3", kind: "ship_upgrade", name: "Ship 08 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 7, stage: 3 },
  { id: "ship_09_stage_2", kind: "ship_upgrade", name: "Ship 09 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 8, stage: 2 },
  { id: "ship_09_stage_3", kind: "ship_upgrade", name: "Ship 09 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 8, stage: 3 },
  { id: "ship_10_stage_2", kind: "ship_upgrade", name: "Ship 10 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 9, stage: 2 },
  { id: "ship_10_stage_3", kind: "ship_upgrade", name: "Ship 10 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 9, stage: 3 },
  { id: "ship_11_stage_2", kind: "ship_upgrade", name: "Ship 11 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 10, stage: 2 },
  { id: "ship_11_stage_3", kind: "ship_upgrade", name: "Ship 11 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 10, stage: 3 },
  { id: "ship_12_stage_2", kind: "ship_upgrade", name: "Ship 12 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 11, stage: 2 },
  { id: "ship_12_stage_3", kind: "ship_upgrade", name: "Ship 12 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 11, stage: 3 },
  { id: "ship_13_stage_2", kind: "ship_upgrade", name: "Ship 13 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 12, stage: 2 },
  { id: "ship_13_stage_3", kind: "ship_upgrade", name: "Ship 13 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 12, stage: 3 },
  { id: "ship_14_stage_2", kind: "ship_upgrade", name: "Ship 14 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 13, stage: 2 },
  { id: "ship_14_stage_3", kind: "ship_upgrade", name: "Ship 14 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 13, stage: 3 },
  { id: "ship_15_stage_2", kind: "ship_upgrade", name: "Ship 15 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 14, stage: 2 },
  { id: "ship_15_stage_3", kind: "ship_upgrade", name: "Ship 15 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 14, stage: 3 },
  { id: "ship_16_stage_2", kind: "ship_upgrade", name: "Ship 16 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 15, stage: 2 },
  { id: "ship_16_stage_3", kind: "ship_upgrade", name: "Ship 16 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 15, stage: 3 },
  { id: "ship_17_stage_2", kind: "ship_upgrade", name: "Ship 17 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 16, stage: 2 },
  { id: "ship_17_stage_3", kind: "ship_upgrade", name: "Ship 17 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 16, stage: 3 },
  { id: "ship_18_stage_2", kind: "ship_upgrade", name: "Ship 18 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 17, stage: 2 },
  { id: "ship_18_stage_3", kind: "ship_upgrade", name: "Ship 18 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 17, stage: 3 },
  { id: "ship_19_stage_2", kind: "ship_upgrade", name: "Ship 19 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 18, stage: 2 },
  { id: "ship_19_stage_3", kind: "ship_upgrade", name: "Ship 19 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 18, stage: 3 },
  { id: "ship_20_stage_2", kind: "ship_upgrade", name: "Ship 20 · Advanced", description: "Permanent Advanced: twin fire and one free enemy shot hit per life. An active shield also protects against ship collisions.", pricePi: 9.9, shipIndex: 19, stage: 2 },
  { id: "ship_20_stage_3", kind: "ship_upgrade", name: "Ship 20 · Elite", description: "Permanent Elite: stronger twin laser fire and two free enemy shot hits per life. An active shield also protects against ship collisions. Requires Advanced.", pricePi: 19.9, shipIndex: 19, stage: 3 }
] as const;

export const armorBonusFromPaid = (productIds: readonly string[]) => hangarCatalog
  .filter(item => item.kind === "armor" && productIds.includes(item.id))
  .reduce((bonus, item) => bonus + (item.kind === "armor" ? item.bonusHearts : 0), 0);

export const findOffer = (id: unknown) => hangarCatalog.find(item => item.id === id);

export const shipUpgradePrerequisite = (offer: typeof hangarCatalog[number]) =>
  offer.kind === "ship_upgrade" && offer.stage === 3
    ? `ship_${String(offer.shipIndex + 1).padStart(2, "0")}_stage_2`
    : null;
