import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { useLocale } from '../i18n';
import { axiosClient } from '../lib/axiosClient';
import { avatarIds } from '../../../backend/src/pilotRules';
import { countryCodes } from '../../../backend/src/countries';
import PilotAvatar, { type Avatar } from '../components/PilotAvatar';
import AvatarCropper, { type AvatarCropperHandle } from '../components/AvatarCropper';
export type Profile={username:string;bio:string;country:string;avatar:Avatar;level:number;serviceRank:{name:string;symbol:string};badges:string[];favorites:string[];network:string};
import { badgeNames, countryFlag } from '../lib/pilotPresentation';
export default function PilotProfile({username,onClose,onSaved}:{username?:string;onClose:()=>void;onSaved?:()=>void}){
 const {locale,t}=useLocale();const dialog=useRef<HTMLDialogElement>(null),cropper=useRef<AvatarCropperHandle>(null);const [profile,setProfile]=useState<Profile|null>(null),[status,setStatus]=useState('loading'),[busy,setBusy]=useState(false),[cropBusy,setCropBusy]=useState(false),[file,setFile]=useState<File|null>(null),[countrySearch,setCountrySearch]=useState('');const own=!username;
 useEffect(()=>{const d=dialog.current,previous=document.activeElement as HTMLElement|null;d?.showModal();return()=>{d?.close();if(previous?.isConnected)previous.focus();};},[]);
 useEffect(()=>{let active=true;axiosClient.get<Profile>(username?`/pilots/public/${encodeURIComponent(username)}`:'/pilots/me').then(({data})=>{if(active){setProfile(data);setStatus('ready');}},()=>{if(active)setStatus('error');});return()=>{active=false;};},[username]);
 const save=async(avatar?:Avatar)=>{if(!profile||busy)return;setBusy(true);try{const {data}=await axiosClient.put<Profile>('/pilots/me',{bio:profile.bio,country:profile.country,avatar:avatar===undefined?profile.avatar:avatar,favorites:profile.favorites});setProfile(data);setStatus('saved');onSaved?.();return true;}catch{setStatus('error');return false;}finally{setBusy(false);}};
 const countries=new Intl.DisplayNames([locale],{type:'region'});
 const change=(patch:Partial<Profile>)=>{setStatus('ready');setProfile(p=>p?{...p,...patch}:p);};
 return createPortal(<dialog ref={dialog} className="pilot-profile metallic-dialog" aria-labelledby="pilot-profile-title" onCancel={e=>{e.preventDefault();e.stopPropagation();onClose();}}><header><h2 id="pilot-profile-title">{t(own?'My pilot profile':'Pilot profile')}</h2><button type="button" onClick={onClose} aria-label={t('Close')}>×</button></header>
 {status==='loading'&&<p role="status">{t('Loading…')}</p>}{status==='error'&&<p role="alert">{t('Profile unavailable. Please retry.')}</p>}{status==='saved'&&<p role="status">{t('Profile saved')}</p>}
 {profile&&<><section className="pilot-identity"><PilotAvatar avatar={profile.avatar} name={profile.username}/><div><h3>@{profile.username}</h3><p>{profile.serviceRank.symbol} {t(profile.serviceRank.name)} · {t('Profile level')} {new Intl.NumberFormat(locale).format(profile.level)}</p>{profile.country&&<p>{countryFlag(profile.country)} {countries.of(profile.country)}</p>}<p className="pilot-bio">{profile.bio}</p></div></section>
 {!own&&<div className="favorite-badges">{profile.favorites.map(id=><figure key={id}><img src={`/badges/${id}.svg`} alt={t(badgeNames[id])}/><figcaption>{t(badgeNames[id])}</figcaption></figure>)}</div>}
 {own&&<><label>{t('Short bio')}<textarea maxLength={160} value={profile.bio} onChange={e=>change({bio:e.target.value})}/></label><label>{t('Country (optional)')}<input type="search" value={countrySearch} onChange={e=>setCountrySearch(e.target.value)} placeholder={t('Search')}/><select value={profile.country} onChange={e=>change({country:e.target.value})}><option value="">{t('Not specified')}</option>{countryCodes.filter(code=>code===profile.country||`${code} ${countries.of(code)}`.toLocaleLowerCase().includes(countrySearch.trim().toLocaleLowerCase())).map(code=><option key={code} value={code}>{countryFlag(code)} {countries.of(code)}</option>)}</select></label>
 <h3>{t('Avatar')}</h3><div className="avatar-grid">{avatarIds.map(id=><button type="button" key={id} aria-label={id} aria-pressed={profile.avatar?.kind==='builtin'&&profile.avatar.id===id} onClick={()=>change({avatar:{kind:'builtin',id}})}><img src={`/pilots/${id}.svg`} alt="" width={128} height={128}/></button>)}</div><label className="avatar-upload">{t('Upload image')}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const image=e.target.files?.[0];if(image&&image.size<=10_000_000){setStatus('ready');setFile(image);}else if(image)setStatus('error');e.target.value='';}}/></label><button type="button" onClick={()=>change({avatar:null})}>{t('Remove image')}</button>
 {file&&<AvatarCropper key={`${file.name}-${file.lastModified}-${file.size}`} ref={cropper} file={file} onBusyChange={setCropBusy} onDone={async image=>{if(await save({kind:'upload',image}))setFile(null);else throw Error('profile_save_failed');}} onCancel={()=>{setFile(null);setStatus('ready');}}/>}
 <h3>{t('Achievement badges')}</h3><p>{t('Choose up to three favorite badges. Service rank is separate.')}</p><div className="badge-grid">{Object.entries(badgeNames).map(([id,name])=>{const unlocked=profile.badges.includes(id),selected=profile.favorites.includes(id);return <button key={id} type="button" disabled={!unlocked||!selected&&profile.favorites.length>=3} aria-pressed={selected} onClick={()=>change({favorites:selected?profile.favorites.filter(b=>b!==id):[...profile.favorites,id]})}><img src={`/badges/${id}.svg`} alt=""/><b>{t(name)}</b><small>{t(unlocked?'Unlocked':'Locked')}</small></button>;})}</div><div className="profile-actions"><button type="button" className="profile-save" disabled={busy||cropBusy} onClick={()=>{if(file)void cropper.current?.save();else void save();}}>{t(busy||cropBusy?'Saving…':'Save profile')}</button><button type="button" onClick={()=>change({bio:'',country:'',avatar:null,favorites:[]})}>{t('Clear profile details')}</button></div></>}
 </>}<button type="button" onClick={onClose}>{t('Close')}</button></dialog>,document.body);
}
