import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url), sharp=require('sharp');
const {sanitizeAvatar}=require('../../build/avatarImage.js');
const {unlockedBadges,verifiedBlockBadges}=require('../../build/pilotRules.js');
const {standardShips}=require('../../build/playerSave.js');
const mount=require('../../build/handlers/pilots.js').default;
const routes={};mount({get:(p,h)=>routes['GET '+p]=h,put:(p,h)=>routes['PUT '+p]=h});
function harness(){const users=[{uid:'a',username:'Pilot',rewardsByNetwork:{testnet:{highestLevel:42,bossWins:{1:1}}}},{uid:'b',username:'Other'}];let writes=0;const collection={findOne:async q=>structuredClone(users.find(u=>Object.entries(q).every(([k,v])=>u[k]===v))),updateOne:async(q,u)=>{writes++;const user=users.find(u=>u.uid===q.uid);for(const [path,value]of Object.entries(u.$set)){const [key,network]=path.split('.');(user[key]??={})[network]=value;}return {modifiedCount:1};}};return {users,get writes(){return writes;},async call(method,body,uid='a',network='testnet',username){const req={body,params:{username},session:uid?{currentUser:{uid}}:{},get:()=>network,app:{locals:{userCollection:collection}}};const res={code:200,status(c){this.code=c;return this;},json(b){this.body=b;return this;}};await routes[method](req,res);return res;}};}
const profile={bio:' Hi ',country:'AT',avatar:{kind:'builtin',id:'trojan-wolf'},favorites:['first-boss']};
test('profiles require verified account, isolate networks and reject locked favorites without gameplay writes',async()=>{const h=harness();assert.equal((await h.call('PUT /me',profile,null)).code,401);assert.equal((await h.call('PUT /me',{...profile,favorites:['final-boss']})).code,400);assert.equal(h.writes,0);const before=structuredClone(h.users[0].rewardsByNetwork);assert.equal((await h.call('PUT /me',{...profile,uid:'b'})).code,200);assert.equal(h.users[0].pilotProfileByNetwork.testnet.bio,'Hi');assert.equal(h.users[1].pilotProfileByNetwork,undefined);assert.deepEqual(h.users[0].rewardsByNetwork,before);assert.equal((await h.call('GET /me',null,'a','mainnet')).body.bio,'');const publicProfile=(await h.call('GET /public/:username',null,null,'testnet','Pilot')).body;assert.equal(publicProfile.uid,undefined);assert.equal(publicProfile.level,5);assert.equal(publicProfile.country,'AT');assert.equal((await h.call('PUT /me',{...profile,country:'XX'})).code,400);assert.equal((await h.call('PUT /me',{...profile,avatar:null,favorites:[],bio:'',country:''})).code,200);assert.equal(h.users[0].pilotProfileByNetwork.testnet.avatar,null);});
test('avatars decode as 128px WebP, strip metadata and reject wrong dimensions, formats and overlimit input',async()=>{const bytes=await sharp({create:{width:128,height:128,channels:3,background:'#658'}}).withExif({IFD0:{Artist:'PRIVATE'}}).webp().toBuffer();const clean=await sanitizeAvatar('data:image/webp;base64,'+bytes.toString('base64'));const output=Buffer.from(clean.split(',')[1],'base64'),meta=await sharp(output).metadata();assert.equal(meta.width,128);assert.equal(meta.height,128);assert.equal(meta.format,'webp');assert.equal(meta.exif,undefined);assert.ok(output.length<=20480);const wrong=await sharp({create:{width:256,height:128,channels:3,background:'#658'}}).webp().toBuffer();await assert.rejects(sanitizeAvatar('data:image/webp;base64,'+wrong.toString('base64')));await assert.rejects(sanitizeAvatar('data:image/png;base64,'+bytes.toString('base64')));await assert.rejects(sanitizeAvatar('data:image/webp;base64,'+Buffer.alloc(20481).toString('base64')));});
test('six badges use network evidence; legacy missing damage never implies a perfect block',()=>{const bossWins=Object.fromEntries(Array.from({length:10},(_,i)=>[i+1,1]));bossWins[50]=1;const user={rewardsByNetwork:{testnet:{bossWins}},playerByNetwork:{testnet:{fleet:Object.fromEntries(standardShips.map(id=>[id,{grey:1}]))}},badgeEvidenceByNetwork:{testnet:{perfectFormation:true,highCombo:true}}};assert.equal(unlockedBadges(user,'testnet').length,6);assert.deepEqual(unlockedBadges(user,'mainnet'),[]);assert.deepEqual(unlockedBadges({rewardsByNetwork:{testnet:{bossWins:{1:0.5}}},playerByNetwork:{testnet:{fleet:Object.fromEntries(standardShips.map(id=>[id,{grey:0.5}]))}}},'testnet'),[]);const event={kind:'block',stage:1};const snapshot={damageCount:0,comboTotal:10,destroyed:20,score:500,hearts:3};assert.deepEqual(verifiedBlockBadges({lastStart:{badgeMetrics:1,startSector:1}},event,snapshot),{perfectFormation:true,highCombo:true});assert.equal(verifiedBlockBadges({lastStart:{startSector:1}},event,snapshot).perfectFormation,undefined);assert.equal(verifiedBlockBadges({mission:{sector:1,phase:'normal',damageAtStart:-1,destroyedAtStart:0,snapshot:{hearts:2}}},event,snapshot).perfectFormation,undefined);assert.deepEqual(verifiedBlockBadges({mission:{sector:2,phase:'normal'}},event,snapshot),{});});

test('Safari PNG fallback accepts only a resized avatar and stores metadata-free WebP',async()=>{
 const png=await sharp({create:{width:128,height:128,channels:4,background:'#346789'}}).withMetadata().png().toBuffer();
 const clean=await sanitizeAvatar('data:image/png;base64,'+png.toString('base64'));
 assert.match(clean,/^data:image\/webp;base64,/);
 const bytes=Buffer.from(clean.split(',')[1],'base64'),meta=await sharp(bytes).metadata();
 assert.equal(meta.width,128);assert.equal(meta.height,128);assert.equal(meta.format,'webp');assert.equal(meta.exif,undefined);assert.ok(bytes.length<=20480);
 const large=await sharp({create:{width:129,height:128,channels:3,background:'#346789'}}).png().toBuffer();
 await assert.rejects(sanitizeAvatar('data:image/png;base64,'+large.toString('base64')));
 await assert.rejects(sanitizeAvatar('data:image/png;base64,'+Buffer.alloc(70001).toString('base64')));
 await assert.rejects(sanitizeAvatar('data:image/webp;base64,'+png.toString('base64')));
});
